version: "3"
services:
  oauth-bot:
    image: python:3.11
    command: bash -c "pip install -r requirements.txt && python main.py"
    restart: unless-stopped
    volumes:
      - ./:/app  # Mounts your local project directory to the container's /app directory
    env_file: .env  # Uses the .env file for environment variables
    ports:
      - "3000:3000"  # Maps host port 3000 to container port 3000

